title: Lviv Dev Club
description: > #
  Let's become the best together
url: "https://lvivdevclub.github.io/"

githuburl: https://github.com/LvivDevClub

# Google services
google_analytics: UA-1596745-44

theme: jekyll-theme-cayman
paginate: 5
plugins:
  - jekyll-feed
